version: '3.8'

services:
  app:
    build:
      context: .
    container_name: sso_app
    env_file: ./.env
    ports: 
      - 4000:4000
    depends_on: 
      - db
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: salar
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
